#!/system/bin/sh
#Author: Asiier
#Settings By: Asiier
#Device: One Plus 5
echo Hotpluging CPU1 and CPU3
chmod 644 /sys/devices/system/cpu/cpu1/online
chmod 644 /sys/devices/system/cpu/cpu5/online
echo 0 > /sys/devices/system/cpu/cpu1/online
echo 0 > /sys/devices/system/cpu/cpu5/online
chmod 444 /sys/devices/system/cpu/cpu1/online
chmod 444 /sys/devices/system/cpu/cpu5/online
